### ISSUE TITLE
Manubot Spell Check

### ISSUE THREAD

**Issue by cgreene** [greenelab/knowledge-graph-review#54]
FYI @agitter created a way to do spellcheck in manubot using appveyor. You may want to enable it and see how well it works in this project. I think the PR is open but it may be possible to easily port it here (or simply download and run it manually in the manubot environment): https://github.com/manubot/rootstock/pull/333

**Comment by cgreene** [comment]
This is an example of @agitter implementing spellchecking in an existing manuscript - it's super helpful! https://github.com/greenelab/covid19-review/pull/261

**Comment by agitter** [comment]
Thanks @danich1 for the grep idea to search for the instances of misspelled words.  That made it much more practical to fix mistakes.

That pull request revealed some bugs in the rootstock implementation.  I'll migrate the fixes back upstream to rootstock but may wait for more live testing on the COVID-19 manuscript first.
